BADFRUIT_KEY: YOUR_BF_KEY
GOOGLE_AJAX_REFERRER: www.rescore.io
USER_AGENT_STRING: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.854.0 Safari/535.2"
ADMIN_USERNAME: ADMIN_PASSWORD
ADMIN_PASSWORD: ADMIN_USERNAME
